# Title: Project 3 Milestone #2
# Name: Maxwell Yung
# Date: 4/21/25

Import pandas, read in data file

In [2]:
import pandas as pd
datafile = "Recalls_Data.csv"
df = pd.read_csv(datafile)

Now analyze raw data

In [3]:
df

,Report Received Date,NHTSA ID,Recall Link,Manufacturer,Subject,Component,Mfr Campaign Number,Recall Type,Potentially Affected,Recall Description,Consequence Summary,Corrective Action,Park Outside Advisory,Do Not Drive Advisory,Completion Rate % (Blank - Not Reported)
0,04/16/2026,26E021000,Go to Recall (https://www.nhtsa.gov/recalls?nh...,"Chrysler (FCA US, LLC)",Engine Failure May Cause Fire or Loss of Drive...,NaN,33D,Equipment,2689,"Chrysler (FCA US, LLC) is recalling certain Mo...",A loss of drive power increases the risk of a ...,Dealers will inspect and replace the engine as...,No,No,NaN
1,04/16/2026,26V244000,Go to Recall (https://www.nhtsa.gov/recalls?nh...,"Chrysler (FCA US, LLC)",Loss of Electronic Stability Control/FMVSS 126,ELECTRONIC STABILITY CONTROL (ESC),36D,Vehicle,6605,"Chrysler (FCA US, LLC) is recalling certain 20...",A loss of electronic stability control increas...,Dealers will replace the steering column contr...,No,No,NaN
2,04/15/2026,26V241000,Go to Recall (https://www.nhtsa.gov/recalls?nh...,"Winnebago Industries, Inc.",Missing Side Reflectors/FMVSS 108,EXTERIOR LIGHTING,204,Vehicle,20,"Winnebago Industries, Inc. (Winnebago) is reca...",Missing reflectors can reduce the visibility o...,"Dealers will install reflectors, free of charg...",No,No,NaN
3,04/14/2026,26V237000,Go to Recall (https://www.nhtsa.gov/recalls?nh...,Ford Motor Company,Unexpected Downshift Can Cause Loss of Control,POWER TRAIN,26S28,Vehicle,1392935,Ford Motor Company (Ford) is recalling certain...,Unexpectedly downshifting into second gear may...,Dealers will update the powertrain control mod...,No,No,NaN
4,04/13/2026,26V234000,Go to Recall (https://www.nhtsa.gov/recalls?nh...,Harley-Davidson Motor Company,Loss of Rear Brakes,"SERVICE BRAKES, HYDRAULIC",0192,Vehicle,16994,Harley-Davidson Motor Company (Harley-Davidson...,Loss of the rear brakes increases the risk of ...,Harley-Davidson will replace the BCM caddy and...,No,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29915,09/29/1966,66V003000,Go to Recall (https://www.nhtsa.gov/recalls?nh...,Honda (American Honda Motor Co.),POWER TRAIN:TRANSMISSION:STANDARD:MANUAL,POWER TRAIN,NR (Not Reported),Vehicle,18572,NaN,NaN,NaN,No,No,NaN
29916,09/19/1966,66V178000,Go to Recall (https://www.nhtsa.gov/recalls?nh...,"RENAULT, INCORPORATED",BRAKES:HYDRAULIC:LINES:HOSE:NON-METALLIC,"SERVICE BRAKES, HYDRAULIC",NR (Not Reported),Vehicle,125,POSSIBILITY THAT THE FRONT BRAKE HOSE END FITT...,IF SUCH LEAKAGE OCCURS AND IF ENOUGH BRAKE FLU...,(REPLACE FRONT BRAKE HOSES AND SEALS.),No,No,NaN
29917,01/19/1966,66V032001,Go to Recall (https://www.nhtsa.gov/recalls?nh...,"General Motors, LLC",STEERING:COLUMN,STEERING,NR (Not Reported),Vehicle,138878,NaN,NaN,NaN,No,No,NaN
29918,01/19/1966,66V032003,Go to Recall (https://www.nhtsa.gov/recalls?nh...,"General Motors, LLC",STEERING:COLUMN,STEERING,NR (Not Reported),Vehicle,70644,NaN,NaN,NaN,No,No,NaN
29919,01/19/1966,66V032004,Go to Recall (https://www.nhtsa.gov/recalls?nh...,"General Motors, LLC",STEERING:COLUMN,STEERING,NR (Not Reported),Vehicle,68184,NaN,NaN,NaN,No,No,NaN

In [4]:
df.describe

<bound method NDFrame.describe of       Report Received Date   NHTSA ID  \
0               04/16/2026  26E021000
1               04/16/2026  26V244000
2               04/15/2026  26V241000
3               04/14/2026  26V237000
4               04/13/2026  26V234000
...                    ...        ...
29915           09/29/1966  66V003000
29916           09/19/1966  66V178000
29917           01/19/1966  66V032001
29918           01/19/1966  66V032003
29919           01/19/1966  66V032004

                                             Recall Link  \
0      Go to Recall (https://www.nhtsa.gov/recalls?nh...
1      Go to Recall (https://www.nhtsa.gov/recalls?nh...
2      Go to Recall (https://www.nhtsa.gov/recalls?nh...
3      Go to Recall (https://www.nhtsa.gov/recalls?nh...
4      Go to Recall (https://www.nhtsa.gov/recalls?nh...
...                                                  ...
29915  Go to Recall (https://www.nhtsa.gov/recalls?nh...
29916  Go to Recall (https://www.nhtsa.gov/recalls?nh...
29917  Go to Recall (https://www.nhtsa.gov/recalls?nh...
29918  Go to Recall (https://www.nhtsa.gov/recalls?nh...
29919  Go to Recall (https://www.nhtsa.gov/recalls?nh...

                           Manufacturer  \
0                Chrysler (FCA US, LLC)
1                Chrysler (FCA US, LLC)
2            Winnebago Industries, Inc.
3                    Ford Motor Company
4         Harley-Davidson Motor Company
...                                 ...
29915  Honda (American Honda Motor Co.)
29916             RENAULT, INCORPORATED
29917               General Motors, LLC
29918               General Motors, LLC
29919               General Motors, LLC

                                                 Subject  \
0      Engine Failure May Cause Fire or Loss of Drive...
1         Loss of Electronic Stability Control/FMVSS 126
2                      Missing Side Reflectors/FMVSS 108
3         Unexpected Downshift Can Cause Loss of Control
4                                    Loss of Rear Brakes
...                                                  ...
29915           POWER TRAIN:TRANSMISSION:STANDARD:MANUAL
29916           BRAKES:HYDRAULIC:LINES:HOSE:NON-METALLIC
29917                                    STEERING:COLUMN
29918                                    STEERING:COLUMN
29919                                    STEERING:COLUMN

                                Component Mfr Campaign Number Recall Type  \
0                                     NaN                 33D   Equipment
1      ELECTRONIC STABILITY CONTROL (ESC)                 36D     Vehicle
2                       EXTERIOR LIGHTING                 204     Vehicle
3                             POWER TRAIN               26S28     Vehicle
4               SERVICE BRAKES, HYDRAULIC                0192     Vehicle
...                                   ...                 ...         ...
29915                         POWER TRAIN   NR (Not Reported)     Vehicle
29916           SERVICE BRAKES, HYDRAULIC   NR (Not Reported)     Vehicle
29917                            STEERING   NR (Not Reported)     Vehicle
29918                            STEERING   NR (Not Reported)     Vehicle
29919                            STEERING   NR (Not Reported)     Vehicle

       Potentially Affected  \
0                      2689
1                      6605
2                        20
3                   1392935
4                     16994
...                     ...
29915                 18572
29916                   125
29917                138878
29918                 70644
29919                 68184

                                      Recall Description  \
0      Chrysler (FCA US, LLC) is recalling certain Mo...
1      Chrysler (FCA US, LLC) is recalling certain 20...
2      Winnebago Industries, Inc. (Winnebago) is reca...
3      Ford Motor Company (Ford) is recalling certain...
4      Harley-Davidson Motor Company (Harley-Davidson...
...                                                  ...
29915                                                NaN
29916  POSSIBILITY THAT THE FRONT BRAKE HOSE END FITT...
29917                                                NaN
29918                                                NaN
29919                                                NaN

                                     Consequence Summary  \
0      A loss of drive power increases the risk of a ...
1      A loss of electronic stability control increas...
2      Missing reflectors can reduce the visibility o...
3      Unexpectedly downshifting into second gear may...
4      Loss of the rear brakes increases the risk of ...
...                                                  ...
29915                                                NaN
29916  IF SUCH LEAKAGE OCCURS AND IF ENOUGH BRAKE FLU...
29917                                                NaN
29918                                                NaN
29919                                                NaN

                                       Corrective Action  \
0      Dealers will inspect and replace the engine as...
1      Dealers will replace the steering column contr...
2      Dealers will install reflectors, free of charg...
3      Dealers will update the powertrain control mod...
4      Harley-Davidson will replace the BCM caddy and...
...                                                  ...
29915                                                NaN
29916             (REPLACE FRONT BRAKE HOSES AND SEALS.)
29917                                                NaN
29918                                                NaN
29919                                                NaN

      Park Outside Advisory  Do Not Drive Advisory  \
0                         No                    No
1                         No                    No
2                         No                    No
3                         No                    No
4                         No                    No
...                      ...                   ...
29915                     No                    No
29916                     No                    No
29917                     No                    No
29918                     No                    No
29919                     No                    No

       Completion Rate % (Blank - Not Reported)
0                                           NaN
1                                           NaN
2                                           NaN
3                                           NaN
4                                           NaN
...                                         ...
29915                                       NaN
29916                                       NaN
29917                                       NaN
29918                                       NaN
29919                                       NaN

[29920 rows x 15 columns]>

In [5]:
df.columns

Index(['Report Received Date', 'NHTSA ID', 'Recall Link', 'Manufacturer',
       'Subject', 'Component', 'Mfr Campaign Number', 'Recall Type',
       'Potentially Affected', 'Recall Description', 'Consequence Summary',
       'Corrective Action', 'Park Outside Advisory ', 'Do Not Drive Advisory',
       'Completion Rate % (Blank - Not Reported)'],
      dtype='object')

In [6]:
df.shape

(29920, 15)

In [7]:
df.dtypes

Report Received Date                         object
NHTSA ID                                     object
Recall Link                                  object
Manufacturer                                 object
Subject                                      object
Component                                    object
Mfr Campaign Number                          object
Recall Type                                  object
Potentially Affected                          int64
Recall Description                           object
Consequence Summary                          object
Corrective Action                            object
Park Outside Advisory                        object
Do Not Drive Advisory                        object
Completion Rate % (Blank - Not Reported)    float64
dtype: object

In [8]:
df.head()

,Report Received Date,NHTSA ID,Recall Link,Manufacturer,Subject,Component,Mfr Campaign Number,Recall Type,Potentially Affected,Recall Description,Consequence Summary,Corrective Action,Park Outside Advisory,Do Not Drive Advisory,Completion Rate % (Blank - Not Reported)
0,04/16/2026,26E021000,Go to Recall (https://www.nhtsa.gov/recalls?nh...,"Chrysler (FCA US, LLC)",Engine Failure May Cause Fire or Loss of Drive...,NaN,33D,Equipment,2689,"Chrysler (FCA US, LLC) is recalling certain Mo...",A loss of drive power increases the risk of a ...,Dealers will inspect and replace the engine as...,No,No,NaN
1,04/16/2026,26V244000,Go to Recall (https://www.nhtsa.gov/recalls?nh...,"Chrysler (FCA US, LLC)",Loss of Electronic Stability Control/FMVSS 126,ELECTRONIC STABILITY CONTROL (ESC),36D,Vehicle,6605,"Chrysler (FCA US, LLC) is recalling certain 20...",A loss of electronic stability control increas...,Dealers will replace the steering column contr...,No,No,NaN
2,04/15/2026,26V241000,Go to Recall (https://www.nhtsa.gov/recalls?nh...,"Winnebago Industries, Inc.",Missing Side Reflectors/FMVSS 108,EXTERIOR LIGHTING,204,Vehicle,20,"Winnebago Industries, Inc. (Winnebago) is reca...",Missing reflectors can reduce the visibility o...,"Dealers will install reflectors, free of charg...",No,No,NaN
3,04/14/2026,26V237000,Go to Recall (https://www.nhtsa.gov/recalls?nh...,Ford Motor Company,Unexpected Downshift Can Cause Loss of Control,POWER TRAIN,26S28,Vehicle,1392935,Ford Motor Company (Ford) is recalling certain...,Unexpectedly downshifting into second gear may...,Dealers will update the powertrain control mod...,No,No,NaN
4,04/13/2026,26V234000,Go to Recall (https://www.nhtsa.gov/recalls?nh...,Harley-Davidson Motor Company,Loss of Rear Brakes,"SERVICE BRAKES, HYDRAULIC",0192,Vehicle,16994,Harley-Davidson Motor Company (Harley-Davidson...,Loss of the rear brakes increases the risk of ...,Harley-Davidson will replace the BCM caddy and...,No,No,NaN

In [9]:
df.tail()

,Report Received Date,NHTSA ID,Recall Link,Manufacturer,Subject,Component,Mfr Campaign Number,Recall Type,Potentially Affected,Recall Description,Consequence Summary,Corrective Action,Park Outside Advisory,Do Not Drive Advisory,Completion Rate % (Blank - Not Reported)
29915,09/29/1966,66V003000,Go to Recall (https://www.nhtsa.gov/recalls?nh...,Honda (American Honda Motor Co.),POWER TRAIN:TRANSMISSION:STANDARD:MANUAL,POWER TRAIN,NR (Not Reported),Vehicle,18572,NaN,NaN,NaN,No,No,NaN
29916,09/19/1966,66V178000,Go to Recall (https://www.nhtsa.gov/recalls?nh...,"RENAULT, INCORPORATED",BRAKES:HYDRAULIC:LINES:HOSE:NON-METALLIC,"SERVICE BRAKES, HYDRAULIC",NR (Not Reported),Vehicle,125,POSSIBILITY THAT THE FRONT BRAKE HOSE END FITT...,IF SUCH LEAKAGE OCCURS AND IF ENOUGH BRAKE FLU...,(REPLACE FRONT BRAKE HOSES AND SEALS.),No,No,NaN
29917,01/19/1966,66V032001,Go to Recall (https://www.nhtsa.gov/recalls?nh...,"General Motors, LLC",STEERING:COLUMN,STEERING,NR (Not Reported),Vehicle,138878,NaN,NaN,NaN,No,No,NaN
29918,01/19/1966,66V032003,Go to Recall (https://www.nhtsa.gov/recalls?nh...,"General Motors, LLC",STEERING:COLUMN,STEERING,NR (Not Reported),Vehicle,70644,NaN,NaN,NaN,No,No,NaN
29919,01/19/1966,66V032004,Go to Recall (https://www.nhtsa.gov/recalls?nh...,"General Motors, LLC",STEERING:COLUMN,STEERING,NR (Not Reported),Vehicle,68184,NaN,NaN,NaN,No,No,NaN

In [10]:
df.sample()

,Report Received Date,NHTSA ID,Recall Link,Manufacturer,Subject,Component,Mfr Campaign Number,Recall Type,Potentially Affected,Recall Description,Consequence Summary,Corrective Action,Park Outside Advisory,Do Not Drive Advisory,Completion Rate % (Blank - Not Reported)
10545,06/21/2016,16V452000,Go to Recall (https://www.nhtsa.gov/recalls?nh...,"International Motors, LLC",Seat May Separate From the Base Frame,NaN,NR (Not Reported),Vehicle,5,"Navistar, Inc. (Navistar) is recalling certain...","In the event of a crash, the seat can separate...",Navistar has already completed the repair work...,No,No,100.0

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29920 entries, 0 to 29919
Data columns (total 15 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Report Received Date                      29920 non-null  object
 1   NHTSA ID                                  29920 non-null  object
 2   Recall Link                               29920 non-null  object
 3   Manufacturer                              29920 non-null  object
 4   Subject                                   29920 non-null  object
 5   Component                                 22322 non-null  object
 6   Mfr Campaign Number                       29681 non-null  object
 7   Recall Type                               29920 non-null  object
 8   Potentially Affected                      29920 non-null  int64
 9   Recall Description                        27519 non-null  object
 10  Consequence Summary                       25032 non-null  object
 11  Corrective Action                         27532 non-null  object
 12  Park Outside Advisory                     29920 non-null  object
 13  Do Not Drive Advisory                     29920 non-null  object
 14  Completion Rate % (Blank - Not Reported)  11239 non-null  float64
dtypes: float64(1), int64(1), object(13)
memory usage: 3.4+ MB