# Title: Final Project Milestone #3
# Name: Maxwell Yung
# Date: 4/28/25

In [2]:
import pandas as pd
datafile = "Recalls_Data.csv"
df = pd.read_csv(datafile)

After analyzing the data last week, the most and really only thing needed to do is simplify column names and drop unnecessary columns.

In [3]:
df

,Report Received Date,NHTSA ID,Recall Link,Manufacturer,Subject,Component,Mfr Campaign Number,Recall Type,Potentially Affected,Recall Description,Consequence Summary,Corrective Action,Park Outside Advisory,Do Not Drive Advisory,Completion Rate % (Blank - Not Reported)
0,04/16/2026,26E021000,Go to Recall (https://www.nhtsa.gov/recalls?nh...,"Chrysler (FCA US, LLC)",Engine Failure May Cause Fire or Loss of Drive...,NaN,33D,Equipment,2689,"Chrysler (FCA US, LLC) is recalling certain Mo...",A loss of drive power increases the risk of a ...,Dealers will inspect and replace the engine as...,No,No,NaN
1,04/16/2026,26V244000,Go to Recall (https://www.nhtsa.gov/recalls?nh...,"Chrysler (FCA US, LLC)",Loss of Electronic Stability Control/FMVSS 126,ELECTRONIC STABILITY CONTROL (ESC),36D,Vehicle,6605,"Chrysler (FCA US, LLC) is recalling certain 20...",A loss of electronic stability control increas...,Dealers will replace the steering column contr...,No,No,NaN
2,04/15/2026,26V241000,Go to Recall (https://www.nhtsa.gov/recalls?nh...,"Winnebago Industries, Inc.",Missing Side Reflectors/FMVSS 108,EXTERIOR LIGHTING,204,Vehicle,20,"Winnebago Industries, Inc. (Winnebago) is reca...",Missing reflectors can reduce the visibility o...,"Dealers will install reflectors, free of charg...",No,No,NaN
3,04/14/2026,26V237000,Go to Recall (https://www.nhtsa.gov/recalls?nh...,Ford Motor Company,Unexpected Downshift Can Cause Loss of Control,POWER TRAIN,26S28,Vehicle,1392935,Ford Motor Company (Ford) is recalling certain...,Unexpectedly downshifting into second gear may...,Dealers will update the powertrain control mod...,No,No,NaN
4,04/13/2026,26V234000,Go to Recall (https://www.nhtsa.gov/recalls?nh...,Harley-Davidson Motor Company,Loss of Rear Brakes,"SERVICE BRAKES, HYDRAULIC",0192,Vehicle,16994,Harley-Davidson Motor Company (Harley-Davidson...,Loss of the rear brakes increases the risk of ...,Harley-Davidson will replace the BCM caddy and...,No,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29915,09/29/1966,66V003000,Go to Recall (https://www.nhtsa.gov/recalls?nh...,Honda (American Honda Motor Co.),POWER TRAIN:TRANSMISSION:STANDARD:MANUAL,POWER TRAIN,NR (Not Reported),Vehicle,18572,NaN,NaN,NaN,No,No,NaN
29916,09/19/1966,66V178000,Go to Recall (https://www.nhtsa.gov/recalls?nh...,"RENAULT, INCORPORATED",BRAKES:HYDRAULIC:LINES:HOSE:NON-METALLIC,"SERVICE BRAKES, HYDRAULIC",NR (Not Reported),Vehicle,125,POSSIBILITY THAT THE FRONT BRAKE HOSE END FITT...,IF SUCH LEAKAGE OCCURS AND IF ENOUGH BRAKE FLU...,(REPLACE FRONT BRAKE HOSES AND SEALS.),No,No,NaN
29917,01/19/1966,66V032001,Go to Recall (https://www.nhtsa.gov/recalls?nh...,"General Motors, LLC",STEERING:COLUMN,STEERING,NR (Not Reported),Vehicle,138878,NaN,NaN,NaN,No,No,NaN
29918,01/19/1966,66V032003,Go to Recall (https://www.nhtsa.gov/recalls?nh...,"General Motors, LLC",STEERING:COLUMN,STEERING,NR (Not Reported),Vehicle,70644,NaN,NaN,NaN,No,No,NaN
29919,01/19/1966,66V032004,Go to Recall (https://www.nhtsa.gov/recalls?nh...,"General Motors, LLC",STEERING:COLUMN,STEERING,NR (Not Reported),Vehicle,68184,NaN,NaN,NaN,No,No,NaN

In [4]:
df.columns

Index(['Report Received Date', 'NHTSA ID', 'Recall Link', 'Manufacturer',
       'Subject', 'Component', 'Mfr Campaign Number', 'Recall Type',
       'Potentially Affected', 'Recall Description', 'Consequence Summary',
       'Corrective Action', 'Park Outside Advisory ', 'Do Not Drive Advisory',
       'Completion Rate % (Blank - Not Reported)'],
      dtype='object')

Data before cleaning ^

In [5]:
new_columns = {
    'Report Received Date': 'report_date',
    'NHTSA ID': 'nhtsa_id',
    'Recall Link': 'recall_link',
    'Manufacturer': 'manufacturer',
    'Subject': 'subject',
    'Component': 'component',
    'Mfr Campaign Number': 'campaign_number',
    'Recall Type': 'recall_type',
    'Potentially Affected': 'affected_count',
    'Recall Description': 'description',
    'Consequence Summary': 'consequence',
    'Corrective Action': 'corrective_action',
    'Park Outside Advisory ': 'park_advisory',
    'Do Not Drive Advisory': 'no_drive_advisory',
    'Completion Rate % (Blank - Not Reported)': 'completion_rate',
}

df.rename(columns=new_columns, inplace=True) #thanks copilot

In [6]:
df.columns

Index(['report_date', 'nhtsa_id', 'recall_link', 'manufacturer', 'subject',
       'component', 'campaign_number', 'recall_type', 'affected_count',
       'description', 'consequence', 'corrective_action', 'park_advisory',
       'no_drive_advisory', 'completion_rate'],
      dtype='object')

In [7]:
keep = ['report_date', 'nhtsa_id', 'manufacturer', 'subject', 'component', 'recall_type', 'affected_count', 'description', 'consequence', 'completion_rate']
df = df[keep]

In [8]:
df

,report_date,nhtsa_id,manufacturer,subject,component,recall_type,affected_count,description,consequence,completion_rate
0,04/16/2026,26E021000,"Chrysler (FCA US, LLC)",Engine Failure May Cause Fire or Loss of Drive...,NaN,Equipment,2689,"Chrysler (FCA US, LLC) is recalling certain Mo...",A loss of drive power increases the risk of a ...,NaN
1,04/16/2026,26V244000,"Chrysler (FCA US, LLC)",Loss of Electronic Stability Control/FMVSS 126,ELECTRONIC STABILITY CONTROL (ESC),Vehicle,6605,"Chrysler (FCA US, LLC) is recalling certain 20...",A loss of electronic stability control increas...,NaN
2,04/15/2026,26V241000,"Winnebago Industries, Inc.",Missing Side Reflectors/FMVSS 108,EXTERIOR LIGHTING,Vehicle,20,"Winnebago Industries, Inc. (Winnebago) is reca...",Missing reflectors can reduce the visibility o...,NaN
3,04/14/2026,26V237000,Ford Motor Company,Unexpected Downshift Can Cause Loss of Control,POWER TRAIN,Vehicle,1392935,Ford Motor Company (Ford) is recalling certain...,Unexpectedly downshifting into second gear may...,NaN
4,04/13/2026,26V234000,Harley-Davidson Motor Company,Loss of Rear Brakes,"SERVICE BRAKES, HYDRAULIC",Vehicle,16994,Harley-Davidson Motor Company (Harley-Davidson...,Loss of the rear brakes increases the risk of ...,NaN
...,...,...,...,...,...,...,...,...,...,...
29915,09/29/1966,66V003000,Honda (American Honda Motor Co.),POWER TRAIN:TRANSMISSION:STANDARD:MANUAL,POWER TRAIN,Vehicle,18572,NaN,NaN,NaN
29916,09/19/1966,66V178000,"RENAULT, INCORPORATED",BRAKES:HYDRAULIC:LINES:HOSE:NON-METALLIC,"SERVICE BRAKES, HYDRAULIC",Vehicle,125,POSSIBILITY THAT THE FRONT BRAKE HOSE END FITT...,IF SUCH LEAKAGE OCCURS AND IF ENOUGH BRAKE FLU...,NaN
29917,01/19/1966,66V032001,"General Motors, LLC",STEERING:COLUMN,STEERING,Vehicle,138878,NaN,NaN,NaN
29918,01/19/1966,66V032003,"General Motors, LLC",STEERING:COLUMN,STEERING,Vehicle,70644,NaN,NaN,NaN
29919,01/19/1966,66V032004,"General Motors, LLC",STEERING:COLUMN,STEERING,Vehicle,68184,NaN,NaN,NaN

In [9]:
df.columns

Index(['report_date', 'nhtsa_id', 'manufacturer', 'subject', 'component',
       'recall_type', 'affected_count', 'description', 'consequence',
       'completion_rate'],
      dtype='object')

Data after cleaning ^

In [10]:
df.to_csv('clean.csv')